apiVersion: v2
name: inari-server
description: >-
  Inari control-plane API server (inari-server) — tenant/org management,
  catalog, resources inventory.
type: application
version: 0.1.3
appVersion: 1.4.0
maintainers:
  - name: 7K-Inari
    url: https://github.com/7K-Inari
