apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Tenant.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.serviceName }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
