apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Tenant.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    inari.io/org-id: {{ .Tenant.OrgID }}
    inari.io/tenant: {{ .Tenant.Slug }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.serviceName }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
